asd

diff --git a/.github/workflows/wf_build_artifacts.yaml b/.github/workflows/wf_build_artifacts.yaml
--- a/.github/workflows/wf_build_artifacts.yaml
+++ b/.github/workflows/wf_build_artifacts.yaml
@@ -118,32 +118,32 @@ jobs:
       run: |
         echo "VERSION=$(make get-version VER=${{ inputs.VERSION }})" >> $GITHUB_OUTPUT
 
-    - name: "Wait for remote builder to be ready"
-      run: |
-        set +e
-        max_attempts=6
-        retry_interval=10
+    # - name: "Wait for remote builder to be ready"
+    #   run: |
+    #     set +e
+    #     max_attempts=6
+    #     retry_interval=10
 
-        attempt=1
-        while [ "$attempt" -le "$max_attempts" ]; do
-            echo "Checking SSH connection (attempt $attempt)..."
-            nc -zv ${{ steps.nix-remote-builder.outputs.publicDnsName }} 22
-            if [ $? -eq 0 ]; then
-                echo "success"
-                break
-            else
-                echo "SSH connection failed."
-                if [ "$attempt" -lt "$max_attempts" ]; then
-                    echo "Retrying in $retry_interval seconds..."
-                    sleep "$retry_interval"
-                else
-                    echo "Exceeded maximum connection attempts."
-                    exit 1
-                fi
-            fi
-            ((attempt++))
-        done
-      if: ${{ ( matrix.platform == 'aarch64' ) && steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
+    #     attempt=1
+    #     while [ "$attempt" -le "$max_attempts" ]; do
+    #         echo "Checking SSH connection (attempt $attempt)..."
+    #         nc -zv ${{ steps.nix-remote-builder.outputs.publicDnsName }} 22
+    #         if [ $? -eq 0 ]; then
+    #             echo "success"
+    #             break
+    #         else
+    #             echo "SSH connection failed."
+    #             if [ "$attempt" -lt "$max_attempts" ]; then
+    #                 echo "Retrying in $retry_interval seconds..."
+    #                 sleep "$retry_interval"
+    #             else
+    #                 echo "Exceeded maximum connection attempts."
+    #                 exit 1
+    #             fi
+    #         fi
+    #         ((attempt++))
+    #     done
+    #   if: ${{ ( matrix.platform == 'aarch64' ) && steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
 
     - name: "Build artifact"
       run: |
