asd

diff --git a/.github/workflows/wf_build_artifacts.yaml b/.github/workflows/wf_build_artifacts.yaml
--- a/.github/workflows/wf_build_artifacts.yaml
+++ b/.github/workflows/wf_build_artifacts.yaml
@@ -76,22 +76,22 @@ jobs:
           || export BUILD_NEEDED=yes
         echo BUILD_NEEDED=$BUILD_NEEDED >> $GITHUB_OUTPUT
 
-    # - name: "Setup nix-remote-builder"
-    #   uses: dbarrosop/nix-remote-builder-aws@v0.3.0
-    #   id: nix-remote-builder
-    #   with:
-    #     name: ${{ inputs.NAME }}-${{ inputs.GIT_REF }}
-    #     ami: ami-0a6fe6f4f55f8421a
-    #     instance-type: 't4g.xlarge'
-    #     region: "eu-central-1"
-    #     availability-zone: "eu-central-1c"
-    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-    #   if: ${{ ( matrix.platform == 'aarch64' ) && steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
+    - name: "Setup nix-remote-builder"
+      uses: dbarrosop/nix-remote-builder-aws@v0.3.0
+      id: nix-remote-builder
+      with:
+        name: ${{ inputs.NAME }}-${{ inputs.GIT_REF }}
+        ami: "ami-0859262366689fb6f"
+        instance-type: 't4g.xlarge'
+        region: "eu-central-1"
+        availability-zone: "eu-central-1c"
+        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      if: ${{ ( matrix.platform == 'aarch64' ) && steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
 
-    # - name: "Setup nix-remote-builder in nix.conf"
-    #   run: |
-    #       echo "builders = ssh://${{ steps.nix-remote-builder.outputs.publicDnsName }} aarch64-linux;" >> ~/.config/nix/nix.conf
-    #   if: ${{ ( matrix.platform == 'aarch64' ) && steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
+    - name: "Setup nix-remote-builder in nix.conf"
+      run: |
+          echo "builders = ssh://${{ steps.nix-remote-builder.outputs.publicDnsName }} aarch64-linux;" >> ~/.config/nix/nix.conf
+      if: ${{ ( matrix.platform == 'aarch64' ) && steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
 
     - name: Cache nix store
       uses: actions/cache@v4
@@ -118,32 +118,32 @@ jobs:
       run: |
         echo "VERSION=$(make get-version VER=${{ inputs.VERSION }})" >> $GITHUB_OUTPUT
 
-    # - name: "Wait for remote builder to be ready"
-    #   run: |
-    #     set +e
-    #     max_attempts=6
-    #     retry_interval=10
+    - name: "Wait for remote builder to be ready"
+      run: |
+        set +e
+        max_attempts=6
+        retry_interval=10
 
-    #     attempt=1
-    #     while [ "$attempt" -le "$max_attempts" ]; do
-    #         echo "Checking SSH connection (attempt $attempt)..."
-    #         nc -zv ${{ steps.nix-remote-builder.outputs.publicDnsName }} 22
-    #         if [ $? -eq 0 ]; then
-    #             echo "success"
-    #             break
-    #         else
-    #             echo "SSH connection failed."
-    #             if [ "$attempt" -lt "$max_attempts" ]; then
-    #                 echo "Retrying in $retry_interval seconds..."
-    #                 sleep "$retry_interval"
-    #             else
-    #                 echo "Exceeded maximum connection attempts."
-    #                 exit 1
-    #             fi
-    #         fi
-    #         ((attempt++))
-    #     done
-    #   if: ${{ ( matrix.platform == 'aarch64' ) && steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
+        attempt=1
+        while [ "$attempt" -le "$max_attempts" ]; do
+            echo "Checking SSH connection (attempt $attempt)..."
+            nc -zv ${{ steps.nix-remote-builder.outputs.publicDnsName }} 22
+            if [ $? -eq 0 ]; then
+                echo "success"
+                break
+            else
+                echo "SSH connection failed."
+                if [ "$attempt" -lt "$max_attempts" ]; then
+                    echo "Retrying in $retry_interval seconds..."
+                    sleep "$retry_interval"
+                else
+                    echo "Exceeded maximum connection attempts."
+                    exit 1
+                fi
+            fi
+            ((attempt++))
+        done
+      if: ${{ ( matrix.platform == 'aarch64' ) && steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
 
     - name: "Build artifact"
       run: |
